import { useState } from "react";
import { Button } from "./ui/button";
import { Textarea } from "./ui/textarea";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Mic, Sparkles, Loader2, ChevronDown, ChevronUp } from "lucide-react";
import { toast } from "sonner@2.0.3";
import { scopeOfWorkData } from "../data/scopeOfWork";
import { LineItem } from "../types/project";
import { Alert, AlertDescription } from "./ui/alert";

interface AIBudgetAssistantProps {
  onLineItemsGenerated: (lineItems: LineItem[]) => void;
}

export function AIBudgetAssistant({ onLineItemsGenerated }: AIBudgetAssistantProps) {
  const [description, setDescription] = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const [isListening, setIsListening] = useState(false);
  const [isExpanded, setIsExpanded] = useState(true);

  const handleVoiceInput = () => {
    // Check if browser supports speech recognition
    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    
    if (!SpeechRecognition) {
      toast.error("Voice input is not supported in your browser. Please type your description instead.");
      return;
    }

    const recognition = new SpeechRecognition();
    recognition.lang = 'en-US';
    recognition.continuous = false;
    recognition.interimResults = false;

    recognition.onstart = () => {
      setIsListening(true);
      toast.info("Listening... Speak now!");
    };

    recognition.onresult = (event: any) => {
      const transcript = event.results[0][0].transcript;
      setDescription(prev => prev + " " + transcript);
      toast.success("Voice captured! You can add more or generate budget.");
    };

    recognition.onerror = (event: any) => {
      setIsListening(false);
      toast.error("Voice input error. Please try typing instead.");
      console.error("Speech recognition error:", event.error);
    };

    recognition.onend = () => {
      setIsListening(false);
    };

    recognition.start();
  };

  const parseAIResponse = (aiText: string): LineItem[] => {
    // This is a simple parser - in production, you'd use structured output from OpenAI
    const lines = aiText.split('\n');
    const lineItems: LineItem[] = [];

    for (const line of lines) {
      // Look for patterns like "8' Wall Framing: 60 lf" or "Doors: 3 each"
      for (const scope of scopeOfWorkData) {
        const scopePattern = new RegExp(scope.name.replace(/[()]/g, '\\$&'), 'i');
        if (scopePattern.test(line)) {
          // Extract quantity
          const quantityMatch = line.match(/(\d+(?:\.\d+)?)\s*(?:lf|sqft|each|lump sum)?/i);
          if (quantityMatch) {
            const quantity = parseFloat(quantityMatch[1]);
            const total = quantity * scope.defaultUnitCost;
            
            lineItems.push({
              id: crypto.randomUUID(),
              scopeName: scope.name,
              unitType: scope.unitType,
              quantity,
              unitCost: scope.defaultUnitCost,
              total,
              notes: "Generated by AI - please review and adjust",
            });
          }
        }
      }
    }

    return lineItems;
  };

  const handleGenerate = async () => {
    if (!description.trim()) {
      toast.error("Please describe your project first");
      return;
    }

    setIsGenerating(true);

    try {
      // Build the system prompt with current scope data
      const scopeList = scopeOfWorkData.map(s => 
        `${s.name}: $${s.defaultUnitCost}/${s.unitType}`
      ).join('\n');

      const systemPrompt = `You are a construction budget estimator assistant. You have access to these scopes of work with unit costs:

${scopeList}

Based on the user's project description, estimate quantities for relevant scopes. Use typical construction ratios:
- Wall area (paint) = room perimeter × wall height (typically 8-10 ft)
- Ceiling area (paint) = floor square footage
- Door count: estimate based on room count and privacy needs
- Wall framing: measure in linear feet (straight line length)
- HVAC: total square footage of area being conditioned

Be conservative with estimates and round to reasonable numbers.

Return ONLY a list in this exact format (one per line):
ScopeName: Quantity UnitType

Example:
8' Wall Framing and Drywall: 60 lf
Paint Walls: 2400 sqft
Door & Hardware: 3 each`;

      const response = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${(typeof import.meta !== 'undefined' && import.meta.env?.VITE_OPENAI_API_KEY) || 'YOUR_API_KEY_HERE'}`,
        },
        body: JSON.stringify({
          model: 'gpt-4',
          messages: [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: description }
          ],
          temperature: 0.3,
          max_tokens: 1000,
        }),
      });

      if (!response.ok) {
        // Check if it's an API key issue
        if (response.status === 401) {
          toast.error("OpenAI API key not configured. Please add your API key to use AI features.");
        } else {
          throw new Error(`API error: ${response.status}`);
        }
        setIsGenerating(false);
        return;
      }

      const data = await response.json();
      const aiText = data.choices[0].message.content;

      // Parse AI response into line items
      const generatedItems = parseAIResponse(aiText);

      if (generatedItems.length === 0) {
        toast.error("Could not generate line items. Please try rephrasing your description or use manual entry.");
        setIsGenerating(false);
        return;
      }

      // Pass generated items to parent
      onLineItemsGenerated(generatedItems);
      toast.success(`Generated ${generatedItems.length} line items! Review and adjust as needed.`);
      
      // Clear description after successful generation
      setDescription("");
      
    } catch (error) {
      console.error('AI generation error:', error);
      toast.error("AI generation failed. Please use manual entry or try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Card className="border-purple-200 bg-gradient-to-br from-purple-50/50 to-blue-50/50 dark:from-purple-950/20 dark:to-blue-950/20">
      <CardHeader>
        <div 
          className="flex items-center justify-between cursor-pointer"
          onClick={() => setIsExpanded(!isExpanded)}
        >
          <CardTitle className="text-lg md:text-xl flex items-center gap-2">
            <Sparkles className="size-5 text-purple-600" />
            Quick Start with AI (Optional)
          </CardTitle>
          <Button variant="ghost" size="sm" className="h-auto p-1">
            {isExpanded ? <ChevronUp className="size-4" /> : <ChevronDown className="size-4" />}
          </Button>
        </div>
        {isExpanded && (
          <p className="text-sm text-muted-foreground">
            Describe your project in plain English or use voice input. AI will suggest line items to get you started faster.
          </p>
        )}
      </CardHeader>
      
      {isExpanded && (
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <Textarea
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Example: I'm renovating a 1,500 sqft office space. Need new flooring throughout, paint all walls and ceilings, add 3 private offices with doors, and update 12 light fixtures."
              rows={4}
              className="resize-none"
            />
          </div>

          <div className="flex flex-col sm:flex-row gap-2">
            <Button
              onClick={handleVoiceInput}
              variant="outline"
              disabled={isListening || isGenerating}
              className="flex-1 sm:flex-none"
            >
              {isListening ? (
                <>
                  <Loader2 className="size-4 mr-2 animate-spin" />
                  Listening...
                </>
              ) : (
                <>
                  <Mic className="size-4 mr-2" />
                  Use Voice
                </>
              )}
            </Button>

            <Button
              onClick={handleGenerate}
              disabled={isGenerating || !description.trim()}
              className="flex-1"
            >
              {isGenerating ? (
                <>
                  <Loader2 className="size-4 mr-2 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Sparkles className="size-4 mr-2" />
                  Generate Budget
                </>
              )}
            </Button>
          </div>

          <Alert>
            <AlertDescription className="text-xs">
              <strong>Note:</strong> AI-generated estimates are preliminary and should be reviewed. You can edit all quantities and add/remove line items after generation.
            </AlertDescription>
          </Alert>
        </CardContent>
      )}
    </Card>
  );
}